### ISSUE TITLE
Add ownership type to CSV export

### ISSUE THREAD

**Issue by davevanfleet** [davevanfleet/letter-writer#21]
## Description

Currently, on `/territories`, when a user downloads contacts as a CSV, the "Home Ownership" column is not included.  This data is shown in the table on the UI, but is not present in the downloaded CSV file

<img width="1003" alt="Screen Shot 2022-05-10 at 12 42 03 PM" src="https://user-images.githubusercontent.com/71672729/167679943-e5e34fa2-681e-4695-a544-73bd26de6fdb.png">

## Acceptance Criteria
- "Home Ownership" column should be present and have data (`"Confirmed Owner" | "Owns" | "Rents" | null`) on territory contacts table
- Home ownership data should be present in downloaded CSV and should match the data on the UI

**Comment by GinaVanFleet** [comment]
'home ownership' was present on the downloaded CSV and had data.  the data matched what was on the UI.
